### PR TITLE
fix(ui): fix language change

### LINKED ISSUE #171: Data feeds website defaults to english for some spanish users
For some users, https://feeds.witnet.io redirects to https://feeds.witnet.io/es but for some other users it does not. Also there is not ability to manually change the language

### PR DESCRIPTION
**Pull request by gabaldon**
close #171

### CODE REVIEW

File: packages/ui/components/LanguageSelector.vue [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+
+export default {
+  data() {
+    const selectedLanguage =
+      this.$route.path.split('/').join('') || defaultLocale
+    const expandedLanguages = languages.map((language) => ({
+      ...language,
+      label: language.name,
+    }))
+    console.log('expanded languages', expandedLanguages)
```
Comment (Tommytrg) [inline packages/ui/components/LanguageSelector.vue:34]:
```suggestion
```

File: packages/ui/components/LanguageSelector.vue [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    return {
+      displayBox: false,
```
Comment (Tommytrg) [inline packages/ui/components/LanguageSelector.vue:36]: Are we using this?
```suggestion
```

File: packages/ui/components/LanguageSelector.vue [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+      selected:
+        findLanguage(expandedLanguages, selectedLanguage) ||
+        findLanguage(expandedLanguages, defaultLocale),
+      options: expandedLanguages,
+    }
+  },
+  watch: {
+    selected: {
+      handler(selected) {
+        this.$router.push(`/${selected.code}`)
```
Comment (Tommytrg) [inline packages/ui/components/LanguageSelector.vue:46]: What happens when you are not in the `/` route?

**Review by Tommytrg — CHANGES_REQUESTED** [review]
Do you think we could add some test to ensure this works? Some things we could test are:
- Select a language in root route works
- Select a language in a nested route redirects to the same nested route but with the language prefix
- Selected language is detected when is not the default one

**Review by Tommytrg — APPROVED** [review]
